const PLAN='dd.plans.v3',STATE='dd.state.v1',SYNC_KEY='dd.sync.key.v3';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const dateKey=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const strength={exercises:[['Chest Press',110],['Lat Pulldown',85],['Seated Row',107.5],['Leg Press',310],['Shoulder Press',32.5],['Abdominal Crunch',115]]};
const b64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function decrypt(pass,p){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64(p.salt),iterations:p.iterations,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(p.iv)},key,b64(p.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
async function loadConnected(){try{const p=await fetch(`data/connected.enc.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null);if(!p)return {status:'offline',data:null};const pass=localStorage.getItem(SYNC_KEY);if(!pass)return {status:'locked',payload:p,data:null};try{return {status:'ok',payload:p,data:await decrypt(pass,p)}}catch{return {status:'badkey',payload:p,data:null}}}catch{return {status:'offline',data:null}}}
function hours(h){if(!h)return null;const x=((h.sleepInBedSeconds||0)-(h.sleepAwakeSeconds||0))/3600;return x>0?x:null}
function ageLabel(ts){if(!ts)return'Unknown';const h=Math.max(0,(Date.now()-new Date(ts).getTime())/36e5);return h<1?'Fresh':h<24?`${Math.round(h)}h old`:`${Math.floor(h/24)}d old`}
function makePlan(c){const d=new Date(),gym=[1,3,5].includes(d.getDay()),h=c?.health?.latest,cal=c?.calendar,gmail=c?.gmail,sh=hours(h),snap=[];
if(h)snap.push(['SLEEP',sh?`${sh.toFixed(1)} hr`:'—'],['RESTING HR',h.restingHeartRate?`${h.restingHeartRate} bpm`:'—'],['LAST STEPS',h.steps?.toLocaleString()||'—']);else snap.push(['HEALTH','Unavailable']);
snap.push(['CALENDAR',cal?`${cal.events?.length||0} events`:'Unavailable'],['INBOX',gmail?`${gmail.unreadActionableCount||0} actionable`:'Unavailable'],['SYNC',ageLabel(c?.generatedAt)]);
const today=[];(cal?.events||[]).forEach((e,i)=>today.push({id:`cal-${i}`,label:e.title||'Calendar event',detail:[e.time,e.location].filter(Boolean).join(' · '),info:true}));if(!today.length)today.push({id:'priority',label:'Finish today’s top priority',detail:'Choose one thing worth finishing.'});
if(gmail?.actionItems?.length)gmail.actionItems.slice(0,3).forEach((m,i)=>today.push({id:`mail-${i}`,label:m.label||'Email needs attention',detail:m.detail||'',info:true}));
return {date:dateKey(),createdAt:new Date().toISOString(),dataGeneratedAt:c?.generatedAt||null,theme:gym?'Build strength. Protect recovery.':'Recover on purpose. Keep moving.',snapshot:snap,sections:[
{title:'Today',items:today},{title:'Body',items:gym?[{id:'workout',label:'Complete strength workout',detail:'Log actual reps below',kind:'workout'},{id:'bike',label:'20–30 min moderate bike',detail:'Conversational effort'}]:[{id:'move',label:'30–40 min brisk walk or Ring Fit',detail:'Recovery-day movement'}]},
{title:'Movement',items:[{id:'steps',label:'Reach 5,000 steps',detail:h?`Latest synced day: ${h.steps?.toLocaleString()||'—'} steps`:'A floor, not a streak.'}]},
{title:'Nutrition',items:[{id:'protein',label:`${c?.health?.goals?.proteinG||'150–180'} g protein`},{id:'fiber',label:`${c?.health?.goals?.fiberG||'30–40'} g fiber`},{id:'satfat',label:`Keep saturated fat ${c?.health?.goals?.saturatedFatG||'≤15'} g`}]},
{title:'Mind',items:[{id:'gratitude',label:'Write three things you’re thankful for',kind:'gratitude'}]},
{title:'Health',items:[{id:'health-info',label:h?`RHR ${h.restingHeartRate??'—'} bpm · SpO₂ ${h.bloodOxygen??'—'}% · Resp ${h.respiratoryRate??'—'}/min`:'Connected health data unavailable',detail:c?.health?.labs?`Labs ${c.health.labs.date}: LDL ${c.health.labs.ldl}, TG ${c.health.labs.triglycerides}, HDL ${c.health.labs.hdl}, A1c ${c.health.labs.a1c}%`:'',info:true}]},
{title:'Inbox',items:[{id:'mail-info',label:gmail?.summary||'No inbox summary available',info:true}]},
{title:'Sleep',items:[{id:'sleep',label:`Protect ${c?.health?.goals?.sleepOpportunityHours||'7.5–8.5'} hours for sleep`,detail:sh?`Latest actual sleep ≈ ${sh.toFixed(1)} hr`:'Give tomorrow a fair shot.'}]},{title:'Life',items:[{id:'life',label:'One life-maintenance task',detail:'Home, family, errand, or admin.'}]}],workout:gym?strength:null}}
function unlockScreen(status){document.querySelector('#theme').textContent=status==='badkey'?'That sync key did not work.':'Connected data is encrypted for privacy.';document.querySelector('#snapshot').innerHTML='<div class="pill"><span>V3 DATA</span><b>Locked</b></div>';document.querySelector('#cards').innerHTML=`<article class="card unlock"><h2>Unlock connected data</h2><p>Your health, calendar, and inbox snapshot is encrypted before it is published to GitHub Pages.</p><input id="sync-key" type="password" autocomplete="off" placeholder="Paste your Daily Dashboard sync key"><button id="unlock">Unlock this device</button><small>The key stays only in this browser.</small></article>`;document.querySelector('#score').textContent='—';document.querySelector('#unlock').onclick=()=>{const v=document.querySelector('#sync-key').value.trim();if(v){localStorage.setItem(SYNC_KEY,v);location.reload()}}}
const sync=await loadConnected();document.querySelector('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
if(sync.status==='locked'||sync.status==='badkey'){unlockScreen(sync.status)}else{const connected=sync.data;let plans=get(PLAN,{});if(!plans[dateKey()]){plans[dateKey()]=makePlan(connected);put(PLAN,plans)}const plan=plans[dateKey()];let states=get(STATE,{});states[dateKey()]??={done:{},gratitude:['','',''],workout:{},notes:{}};let state=states[dateKey()];const save=()=>{states[dateKey()]=state;put(STATE,states);renderScore()};document.querySelector('#theme').textContent=plan.theme;document.querySelector('#snapshot').innerHTML=plan.snapshot.map(x=>`<div class="pill"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');
function special(it){if(it.kind==='gratitude')return `<div>${state.gratitude.map((v,i)=>`<input class="gratitude" data-g="${i}" type="text" placeholder="${i+1}. I’m thankful for…" value="${esc(v)}">`).join('')}</div>`;if(it.kind==='workout'&&plan.workout)return `<div>${plan.workout.exercises.map(([n,w])=>`<div class="exercise"><span>${esc(n)}<small>${w} lb target</small></span><input data-ex="${esc(n)}" data-f="reps" type="text" placeholder="10/10/10" value="${esc(state.workout[n]?.reps||'')}"><input data-ex="${esc(n)}" data-f="weight" type="number" step="2.5" placeholder="lb" value="${esc(state.workout[n]?.weight||w)}"></div>`).join('')}</div>`;return''}
function render(){document.querySelector('#cards').innerHTML=plan.sections.map(s=>`<article class="card"><h2>${esc(s.title)}</h2>${s.items.map(it=>it.info?`<div class="item"><label>${esc(it.label)}${it.detail?`<small>${esc(it.detail)}</small>`:''}</label></div>`:`<div class="item ${state.done[it.id]?'done':''}"><input data-id="${esc(it.id)}" type="checkbox" ${state.done[it.id]?'checked':''}><label>${esc(it.label)}${it.detail?`<small>${esc(it.detail)}</small>`:''}${special(it)}</label></div>`).join('')}</article>`).join('');document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{state.done[x.dataset.id]=x.checked;save();render()});document.querySelectorAll('[data-g]').forEach(x=>x.oninput=()=>{state.gratitude[+x.dataset.g]=x.value;save()});document.querySelectorAll('[data-ex]').forEach(x=>x.oninput=()=>{const n=x.dataset.ex;state.workout[n]??={};state.workout[n][x.dataset.f]=x.value;save()});renderScore()}
function renderScore(){const all=plan.sections.flatMap(s=>s.items).filter(i=>!i.info),n=all.filter(i=>state.done[i.id]).length;document.querySelector('#score').textContent=`${n}/${all.length}`}render()}
document.querySelector('#export').onclick=()=>{const b=new Blob([JSON.stringify({plans:get(PLAN,{}),states:get(STATE,{})},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='daily-dashboard-data.json';a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#import').onchange=async e=>{try{const j=JSON.parse(await e.target.files[0].text());if(j.plans&&j.states){put(PLAN,j.plans);put(STATE,j.states);location.reload()}}catch{alert('Could not import that file.')}};
document.querySelector('#forget-key').onclick=()=>{localStorage.removeItem(SYNC_KEY);location.reload()};