import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const SUPA_URL='https://iazjfnkfvykxqbocehju.supabase.co',SUPA_KEY='sb_publishable_SABO8l1ps0HEs9kkV2pKEw_3XR85yIt';
const db=createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const PLAN='dd.plans.v3',STATE='dd.state.v1',SYNC_KEY='dd.sync.key.v3';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const todayKey=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const shift=(k,n)=>{const d=new Date(k+'T12:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function decrypt(pass,p){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64(p.salt),iterations:p.iterations,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(p.iv)},key,b64(p.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
async function connected(){try{const p=await fetch(`data/connected.enc.json?t=${Date.now()}`).then(r=>r.json()),pass=localStorage.getItem(SYNC_KEY);if(!pass)return {locked:true};return {data:await decrypt(pass,p)}}catch{return {data:null}}}
const strength={exercises:[['Chest Press',110],['Lat Pulldown',85],['Seated Row',107.5],['Leg Press',310],['Shoulder Press',32.5],['Abdominal Crunch',115]]};
function hours(h){const x=h?((h.sleepInBedSeconds||0)-(h.sleepAwakeSeconds||0))/3600:0;return x>0?x:null}
function makePlan(c){const gym=[1,3,5].includes(new Date().getDay()),h=c?.health?.latest,sh=hours(h),cal=c?.calendar,g=c?.gmail,snap=[];if(h)snap.push(['SLEEP',sh?`${sh.toFixed(1)} hr`:'—'],['RESTING HR',h.restingHeartRate?`${h.restingHeartRate} bpm`:'—'],['LAST STEPS',h.steps?.toLocaleString()||'—']);snap.push(['CALENDAR',`${cal?.events?.length||0} events`],['INBOX',`${g?.unreadActionableCount||0} actionable`],['CLOUD','Synced']);const t=[];(cal?.events||[]).forEach((e,i)=>t.push({id:`cal-${i}`,label:e.title||'Calendar event',detail:[e.time,e.location].filter(Boolean).join(' · '),info:true}));if(!t.length)t.push({id:'priority',label:'Finish today’s top priority',detail:'Choose one thing worth finishing.'});return {date:todayKey(),createdAt:new Date().toISOString(),theme:gym?'Build strength. Protect recovery.':'Recover on purpose. Keep moving.',snapshot:snap,sections:[{title:'Today',items:t},{title:'Body',items:gym?[{id:'workout',label:'Complete strength workout',detail:'Log actual reps below',kind:'workout'},{id:'bike',label:'20–30 min moderate bike'}]:[{id:'move',label:'30–40 min brisk walk or Ring Fit'}]},{title:'Movement',items:[{id:'steps',label:'Reach 5,000 steps',detail:h?`Latest synced day: ${h.steps||'—'} steps`:''}]},{title:'Nutrition',items:[{id:'protein',label:'150–180 g protein'},{id:'fiber',label:'30–40 g fiber'},{id:'satfat',label:'Keep saturated fat ≤15 g'}]},{title:'Mind',items:[{id:'gratitude',label:'Write three things you’re thankful for',kind:'gratitude'}]},{title:'Health',items:[{id:'health-info',label:h?`RHR ${h.restingHeartRate??'—'} bpm · SpO₂ ${h.bloodOxygen??'—'}% · Resp ${h.respiratoryRate??'—'}/min`:'Health data unavailable',detail:c?.health?.labs?`LDL ${c.health.labs.ldl} · TG ${c.health.labs.triglycerides} · HDL ${c.health.labs.hdl} · A1c ${c.health.labs.a1c}%`:'',info:true}]},{title:'Inbox',items:[{id:'mail-info',label:g?.summary||'No inbox summary',info:true}]},{title:'Sleep',items:[{id:'sleep',label:'Protect 7.5–8.5 hours for sleep'}]},{title:'Life',items:[{id:'life',label:'One life-maintenance task'}]}],workout:gym?strength:null}}
function authScreen(){document.querySelector('#theme').textContent='Sign in once on each device. Your dashboard will follow you.';document.querySelector('#snapshot').innerHTML='';document.querySelector('#cards').innerHTML=`<article class="card unlock"><h2>Cloud account</h2><p>Use the same email on your phone and computer. We’ll email you a secure sign-in link.</p><input id="email" type="email" placeholder="Email address"><button id="signin">Email me a sign-in link</button><small id="auth-msg"></small></article>`;document.querySelector('#signin').onclick=async()=>{const email=document.querySelector('#email').value.trim(),m=document.querySelector('#auth-msg');if(!email)return;const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});m.textContent=error?error.message:'Check your email, then open the sign-in link.'}}
function keyScreen(){document.querySelector('#theme').textContent='Your connected health snapshot is encrypted.';document.querySelector('#cards').innerHTML=`<article class="card unlock"><h2>Unlock connected data</h2><input id="key" type="password" placeholder="Daily Dashboard sync key"><button id="unlock">Unlock</button></article>`;document.querySelector('#unlock').onclick=()=>{const v=document.querySelector('#key').value.trim();if(v){localStorage.setItem(SYNC_KEY,v);location.reload()}}}
const {data:{session}}=await db.auth.getSession();document.querySelector('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
if(!session){authScreen()}else{const conn=await connected();if(conn.locked){keyScreen()}else{const uid=session.user.id,today=todayKey();let {data:rows,error}=await db.from('daily_dashboards').select('day,plan,state,updated_at').order('day',{ascending:true});if(error){document.querySelector('#cards').innerHTML=`<article class="card"><h2>Cloud error</h2><p>${esc(error.message)}</p></article>`}else{let map=Object.fromEntries((rows||[]).map(r=>[r.day,r]));if(!map[today]){let plans=get(PLAN,{}),states=get(STATE,{}),plan=plans[today]||makePlan(conn.data),state=states[today]||{done:{},gratitude:['','',''],workout:{},notes:{}};const {data:r,error:e}=await db.from('daily_dashboards').upsert({user_id:uid,day:today,plan,state},{onConflict:'user_id,day'}).select().single();if(!e)map[today]=r}let view=new URLSearchParams(location.search).get('day')||today;if(view>today)view=today;
async function save(plan,state){put(PLAN,{...get(PLAN,{}),[today]:plan});put(STATE,{...get(STATE,{}),[today]:state});const {error}=await db.from('daily_dashboards').update({state}).eq('day',today);const s=document.querySelector('#cloud-status');s.hidden=false;s.textContent=error?'SAVE FAILED — changes remain cached on this device':'SAVED TO CLOUD';if(!error){map[today].state=structuredClone(state);setTimeout(()=>s.hidden=true,1200)}}
function nav(n){const days=Object.keys(map).sort(),i=days.indexOf(view),j=i+n;if(j>=0&&j<days.length){const u=new URL(location.href),k=days[j];k===today?u.searchParams.delete('day'):u.searchParams.set('day',k);location.href=u}}
function render(){const r=map[view]||map[today],plan=r.plan,state=r.state||{},past=r.day!==today;document.body.classList.toggle('archived',past);document.querySelector('#archive-banner').hidden=!past;document.querySelector('#date').textContent=new Date(r.day+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});document.querySelector('#theme').textContent=plan.theme;document.querySelector('#snapshot').innerHTML=(plan.snapshot||[]).map(x=>`<div class="pill"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');const special=it=>it.kind==='gratitude'?`<div>${(state.gratitude||['','','']).map((v,i)=>past?`<div class="readonly-value ${v?'':'empty'}">${esc(v||'No entry')}</div>`:`<input class="gratitude" data-g="${i}" type="text" placeholder="${i+1}. I’m thankful for…" value="${esc(v)}">`).join('')}</div>`:it.kind==='workout'&&plan.workout?`<div>${plan.workout.exercises.map(([n,w])=>past?`<div class="exercise"><span>${esc(n)}<small>${w} lb target</small></span><div>${esc(state.workout?.[n]?.reps||'—')}</div><div>${esc(state.workout?.[n]?.weight||w)} lb</div></div>`:`<div class="exercise"><span>${esc(n)}<small>${w} lb target</small></span><input data-ex="${esc(n)}" data-f="reps" value="${esc(state.workout?.[n]?.reps||'')}" placeholder="10/10/10"><input data-ex="${esc(n)}" data-f="weight" type="number" step="2.5" value="${esc(state.workout?.[n]?.weight||w)}"></div>`).join('')}</div>`:'';document.querySelector('#cards').innerHTML=plan.sections.map(s=>`<article class="card"><h2>${esc(s.title)}</h2>${s.items.map(it=>it.info?`<div class="item"><label>${esc(it.label)}${it.detail?`<small>${esc(it.detail)}</small>`:''}</label></div>`:`<div class="item ${state.done?.[it.id]?'done':''}"><input data-id="${esc(it.id)}" type="checkbox" ${state.done?.[it.id]?'checked':''} ${past?'disabled':''}><label>${esc(it.label)}${it.detail?`<small>${esc(it.detail)}</small>`:''}${special(it)}</label></div>`).join('')}</article>`).join('');const all=plan.sections.flatMap(s=>s.items).filter(i=>!i.info),done=all.filter(i=>state.done?.[i.id]).length;document.querySelector('#score').textContent=`${done}/${all.length}`;if(!past){document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{state.done??={};state.done[x.dataset.id]=x.checked;save(plan,state);render()});document.querySelectorAll('[data-g]').forEach(x=>x.onchange=()=>{state.gratitude??=['','',''];state.gratitude[+x.dataset.g]=x.value;save(plan,state)});document.querySelectorAll('[data-ex]').forEach(x=>x.onchange=()=>{state.workout??={};state.workout[x.dataset.ex]??={};state.workout[x.dataset.ex][x.dataset.f]=x.value;save(plan,state)})}const days=Object.keys(map).sort(),i=days.indexOf(r.day);document.querySelector('#prev-day').disabled=i<=0;document.querySelector('#next-day').disabled=i>=days.length-1;document.querySelector('#today-day').disabled=!past}
document.querySelector('#prev-day').onclick=()=>nav(-1);document.querySelector('#next-day').onclick=()=>nav(1);document.querySelector('#today-day').onclick=()=>location.href=location.pathname;render()}}}
document.querySelector('#account').onclick=async()=>{if(session){if(confirm(`Signed in as ${session.user.email}. Sign out?`)){await db.auth.signOut();location.reload()}}};document.querySelector('#forget-key').onclick=()=>{localStorage.removeItem(SYNC_KEY);location.reload()};document.querySelector('#export').onclick=()=>{const b=new Blob([JSON.stringify({plans:get(PLAN,{}),states:get(STATE,{})},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='daily-dashboard-local-backup.json';a.click()};document.querySelector('#import').onchange=()=>alert('Cloud sync is now authoritative. Import migration will be added if needed.');