const PLAN='dd.plans.v1', STATE='dd.state.v1';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const key=()=>{let d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const strength={title:'Strength',detail:'Full-body session',exercises:[['Chest Press',110],['Lat Pulldown',85],['Seated Row',107.5],['Leg Press',310],['Shoulder Press',32.5],['Abdominal Crunch',115]]};
function makePlan(){const d=new Date(),day=d.getDay(),gym=[1,3,5].includes(day);return Object.freeze({date:key(),createdAt:new Date().toISOString(),theme:gym?'Build strength. Protect recovery.':'Recover on purpose. Keep moving.',snapshot:[['FITBIT','Not synced'],['CALENDAR','Not synced'],['WEIGHT','Add when useful']],sections:[
{title:'Today',items:[{id:'priority',label:'Finish today’s top priority',detail:'Choose one thing worth finishing.'}]},
{title:'Body',items:gym?[{id:'workout',label:'Complete strength workout',detail:'Log actual reps below',kind:'workout'},{id:'bike',label:'20–30 min moderate bike',detail:'Conversational effort'}]:[{id:'move',label:'30–40 min brisk walk or Ring Fit',detail:'Recovery-day movement'}]},
{title:'Movement',items:[{id:'steps',label:'Reach 5,000 steps',detail:'A floor, not a streak.'}]},
{title:'Nutrition',items:[{id:'protein',label:'150–180 g protein'},{id:'fiber',label:'30–40 g fiber'},{id:'satfat',label:'Keep saturated fat ≤15 g'}]},
{title:'Mind',items:[{id:'gratitude',label:'Write three things you’re thankful for',kind:'gratitude'}]},
{title:'Sleep',items:[{id:'sleep',label:'Protect 7.5–8.5 hours for sleep',detail:'Give tomorrow a fair shot.'}]},
{title:'Life',items:[{id:'life',label:'One life-maintenance task',detail:'Home, family, errand, or admin.'}]}
],workout:gym?strength:null})}
let plans=get(PLAN,{});if(!plans[key()]){plans[key()]=makePlan();put(PLAN,plans)}const plan=plans[key()];let states=get(STATE,{});states[key()]??={done:{},gratitude:['','',''],workout:{},notes:{}};let state=states[key()];const save=()=>{states[key()]=state;put(STATE,states);renderScore()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelector('#date').textContent=new Date(plan.date+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});document.querySelector('#theme').textContent=plan.theme;
document.querySelector('#snapshot').innerHTML=plan.snapshot.map(x=>`<div class="pill"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');
function special(it){if(it.kind==='gratitude')return `<div>${state.gratitude.map((v,i)=>`<input class="gratitude" data-g="${i}" type="text" placeholder="${i+1}. I’m thankful for…" value="${esc(v)}">`).join('')}</div>`;if(it.kind==='workout'&&plan.workout)return `<div>${plan.workout.exercises.map(([n,w])=>`<div class="exercise"><span>${n}<small>${w} lb target</small></span><input data-ex="${n}" data-f="reps" type="text" placeholder="10/10/10" value="${esc(state.workout[n]?.reps||'')}"><input data-ex="${n}" data-f="weight" type="number" step="2.5" placeholder="lb" value="${esc(state.workout[n]?.weight||w)}"></div>`).join('')}</div>`;return ''}
function render(){document.querySelector('#cards').innerHTML=plan.sections.map(s=>`<article class="card"><h2>${s.title}</h2>${s.items.map(it=>`<div class="item ${state.done[it.id]?'done':''}"><input data-id="${it.id}" type="checkbox" ${state.done[it.id]?'checked':''}><label>${it.label}${it.detail?`<small>${it.detail}</small>`:''}${special(it)}</label></div>`).join('')}</article>`).join('');bind();renderScore()}
function bind(){document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{state.done[x.dataset.id]=x.checked;save();render()});document.querySelectorAll('[data-g]').forEach(x=>x.oninput=()=>{state.gratitude[+x.dataset.g]=x.value;save()});document.querySelectorAll('[data-ex]').forEach(x=>x.oninput=()=>{let n=x.dataset.ex;state.workout[n]??={};state.workout[n][x.dataset.f]=x.value;save()})}
function renderScore(){let all=plan.sections.flatMap(s=>s.items),n=all.filter(i=>state.done[i.id]).length;document.querySelector('#score').textContent=`${n}/${all.length}`}
document.querySelector('#export').onclick=()=>{let b=new Blob([JSON.stringify({plans,states},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='daily-dashboard-data.json';a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#import').onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text());if(j.plans&&j.states){put(PLAN,j.plans);put(STATE,j.states);location.reload()}}catch{alert('Could not import that file.')}};render();